{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Profile<uuid='efe3b646acbe4b46b34848999a0e7c25' name='test_aiida'>"
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# AiiDA環境をロード\n",
    "from aiida import load_profile\n",
    "\n",
    "# プロファイルをロード\n",
    "load_profile(\"test_aiida\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<Int: uuid: ca79aa1a-ad97-4834-b28d-eab9b3c73b80 (pk: 144) value: 2>"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Int ノードをインポート\n",
    "from aiida.orm import Int\n",
    "\n",
    "node = Int(2)\n",
    "node.store()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "from aiida.engine import calcfunction\n",
    "\n",
    "\n",
    "@calcfunction\n",
    "def multiply(x, y):\n",
    "    return x * y"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<Int: uuid: 0fe1457f-67f6-4b03-b438-e71040e88489 (pk: 148) value: 15>"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "x = Int(3)\n",
    "y = Int(5)\n",
    "multiply(x, y)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [],
   "source": [
    "from aiida.orm import load_code, load_node, load_group, Dict\n",
    "from aiida.plugins import DataFactory\n",
    "\n",
    "code = load_code('pw@localhost')\n",
    "builder = code.get_builder()\n",
    "\n",
    "structure = load_node(8)\n",
    "builder.structure = structure\n",
    "\n",
    "pseudo_family = load_group('SSSP/1.3/PBE/efficiency')\n",
    "pseudos = pseudo_family.get_pseudos(structure=structure)\n",
    "builder.pseudos = pseudos\n",
    "\n",
    "parameters = {\n",
    "  'CONTROL': {\n",
    "    'calculation': 'scf',  # self-consistent field\n",
    "  },\n",
    "  'SYSTEM': {\n",
    "    'ecutwfc': 30.,  # wave function cutoff in Ry\n",
    "    'ecutrho': 240.,  # density cutoff in Ry\n",
    "  },\n",
    "}\n",
    "builder.parameters = Dict(parameters)\n",
    "\n",
    "KpointsData = DataFactory('core.array.kpoints')\n",
    "kpoints = KpointsData()\n",
    "kpoints.set_kpoints_mesh([4,4,4])\n",
    "builder.kpoints = kpoints\n",
    "\n",
    "builder.metadata.options.resources = {'num_machines': 1}\n",
    "builder.metadata.options.queue_name = \"GroupC\"\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/storage/psql_dos/orm/nodes.py:224: SAWarning: Identity map already had an identity for (<class 'aiida.storage.sqlite_zip.models.DbNode'>, (172,), None), replacing it with newly flushed object.   Are there load operations occurring inside of an event handler within the flush?\n",
      "  session.commit()\n",
      "01/29/2025 07:04:42 PM <1456420> aiida.schedulers.plugins.pbsbaseclasses: [ERROR] There are lines without equals sign! [' case \\\\\"$-\\\\\" in ', ' *v*x*)', ' ;; *v*)', ' ;; *x*)', ' ;; *)', ' ;; esac; fi; unset _mlre _mlIFS; if [ -n \\\\\"${IFS+x}\\\\\" ]; then', ' if [ -n \\\\\"`eval \\\\\\'echo ${\\\\\\'$_mlv\\\\\\'+x}\\\\\\'`\\\\\" ]; then', ' eval `eval ${_mlre} /usr/bin/tclsh /usr/share/Modules/libexec/modulecmd.tcl bash \\\\\\'\\\\\"$@\\\\\"\\\\\\'`; else', ' unset IFS; fi; unset _mlre _mlv _mlrv _mlIFS; if [ -n \\\\\"${_mlshdbg:-}\\\\\" ]; then', ' echo \\\\\"Switching to Modules $swname version\\\\\"; source /usr/share/Modules/init/bash; else', ' eval \\\\\"module $@\\\\\"; else']\n",
      "01/29/2025 07:04:42 PM <1456420> aiida.engine.transports: [ERROR] Exception whilst using transport:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/engine/transports.py\", line 106, in request_transport\n",
      "    yield transport_request.future\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 109, in _get_jobs_from_scheduler\n",
      "    scheduler_response = scheduler.get_jobs(**kwargs)\n",
      "                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/schedulers/scheduler.py\", line 361, in get_jobs\n",
      "    joblist = self._parse_joblist_output(retval, stdout, stderr)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/schedulers/plugins/pbsbaseclasses.py\", line 405, in _parse_joblist_output\n",
      "    raise SchedulerParsingError('There are lines without equals sign.')\n",
      "aiida.schedulers.scheduler.SchedulerParsingError: There are lines without equals sign.\n",
      "\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-87' coro=<JobsList._ensure_updating.<locals>.updating() done, defined at /home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py:179> exception=SchedulerParsingError('There are lines without equals sign.')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/asyncio/tasks.py\", line 314, in __step_run_and_handle_result\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 181, in updating\n",
      "    await self._update_job_info()\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 132, in _update_job_info\n",
      "    self._jobs_cache = await self._get_jobs_from_scheduler()\n",
      "                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 109, in _get_jobs_from_scheduler\n",
      "    scheduler_response = scheduler.get_jobs(**kwargs)\n",
      "                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/schedulers/scheduler.py\", line 361, in get_jobs\n",
      "    joblist = self._parse_joblist_output(retval, stdout, stderr)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/schedulers/plugins/pbsbaseclasses.py\", line 405, in _parse_joblist_output\n",
      "    raise SchedulerParsingError('There are lines without equals sign.')\n",
      "aiida.schedulers.scheduler.SchedulerParsingError: There are lines without equals sign.\n",
      "01/29/2025 07:04:42 PM <1456420> aiida.orm.nodes.process.calculation.calcjob.CalcJobNode: [ERROR] iteration 1 of do_update excepted, retrying after 20 seconds\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/engine/utils.py\", line 205, in exponential_backoff_retry\n",
      "    result = await coro()\n",
      "             ^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/tasks.py\", line 195, in do_update\n",
      "    job_info = await cancellable.with_interrupt(update_request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/engine/utils.py\", line 115, in with_interrupt\n",
      "    result = await next(wait_iter)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/asyncio/tasks.py\", line 631, in _wait_for_one\n",
      "    return f.result()  # May raise f.exception().\n",
      "           ^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/asyncio/futures.py\", line 202, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 132, in _update_job_info\n",
      "    self._jobs_cache = await self._get_jobs_from_scheduler()\n",
      "                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 109, in _get_jobs_from_scheduler\n",
      "    scheduler_response = scheduler.get_jobs(**kwargs)\n",
      "                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/schedulers/scheduler.py\", line 361, in get_jobs\n",
      "    joblist = self._parse_joblist_output(retval, stdout, stderr)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/schedulers/plugins/pbsbaseclasses.py\", line 405, in _parse_joblist_output\n",
      "    raise SchedulerParsingError('There are lines without equals sign.')\n",
      "aiida.schedulers.scheduler.SchedulerParsingError: There are lines without equals sign.\n",
      "01/29/2025 07:05:03 PM <1456420> aiida.schedulers.plugins.pbsbaseclasses: [ERROR] There are lines without equals sign! [' case \\\\\"$-\\\\\" in ', ' *v*x*)', ' ;; *v*)', ' ;; *x*)', ' ;; *)', ' ;; esac; fi; unset _mlre _mlIFS; if [ -n \\\\\"${IFS+x}\\\\\" ]; then', ' if [ -n \\\\\"`eval \\\\\\'echo ${\\\\\\'$_mlv\\\\\\'+x}\\\\\\'`\\\\\" ]; then', ' eval `eval ${_mlre} /usr/bin/tclsh /usr/share/Modules/libexec/modulecmd.tcl bash \\\\\\'\\\\\"$@\\\\\"\\\\\\'`; else', ' unset IFS; fi; unset _mlre _mlv _mlrv _mlIFS; if [ -n \\\\\"${_mlshdbg:-}\\\\\" ]; then', ' echo \\\\\"Switching to Modules $swname version\\\\\"; source /usr/share/Modules/init/bash; else', ' eval \\\\\"module $@\\\\\"; else']\n",
      "01/29/2025 07:05:03 PM <1456420> aiida.engine.transports: [ERROR] Exception whilst using transport:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/engine/transports.py\", line 106, in request_transport\n",
      "    yield transport_request.future\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 109, in _get_jobs_from_scheduler\n",
      "    scheduler_response = scheduler.get_jobs(**kwargs)\n",
      "                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/schedulers/scheduler.py\", line 361, in get_jobs\n",
      "    joblist = self._parse_joblist_output(retval, stdout, stderr)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/schedulers/plugins/pbsbaseclasses.py\", line 405, in _parse_joblist_output\n",
      "    raise SchedulerParsingError('There are lines without equals sign.')\n",
      "aiida.schedulers.scheduler.SchedulerParsingError: There are lines without equals sign.\n",
      "\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-88' coro=<JobsList._ensure_updating.<locals>.updating() done, defined at /home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py:179> exception=SchedulerParsingError('There are lines without equals sign.')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/asyncio/tasks.py\", line 314, in __step_run_and_handle_result\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 181, in updating\n",
      "    await self._update_job_info()\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 132, in _update_job_info\n",
      "    self._jobs_cache = await self._get_jobs_from_scheduler()\n",
      "                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 109, in _get_jobs_from_scheduler\n",
      "    scheduler_response = scheduler.get_jobs(**kwargs)\n",
      "                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/schedulers/scheduler.py\", line 361, in get_jobs\n",
      "    joblist = self._parse_joblist_output(retval, stdout, stderr)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/schedulers/plugins/pbsbaseclasses.py\", line 405, in _parse_joblist_output\n",
      "    raise SchedulerParsingError('There are lines without equals sign.')\n",
      "aiida.schedulers.scheduler.SchedulerParsingError: There are lines without equals sign.\n",
      "01/29/2025 07:05:03 PM <1456420> aiida.orm.nodes.process.calculation.calcjob.CalcJobNode: [ERROR] iteration 2 of do_update excepted, retrying after 40 seconds\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/engine/utils.py\", line 205, in exponential_backoff_retry\n",
      "    result = await coro()\n",
      "             ^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/tasks.py\", line 195, in do_update\n",
      "    job_info = await cancellable.with_interrupt(update_request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/engine/utils.py\", line 115, in with_interrupt\n",
      "    result = await next(wait_iter)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/asyncio/tasks.py\", line 631, in _wait_for_one\n",
      "    return f.result()  # May raise f.exception().\n",
      "           ^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/asyncio/futures.py\", line 202, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 132, in _update_job_info\n",
      "    self._jobs_cache = await self._get_jobs_from_scheduler()\n",
      "                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 109, in _get_jobs_from_scheduler\n",
      "    scheduler_response = scheduler.get_jobs(**kwargs)\n",
      "                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/schedulers/scheduler.py\", line 361, in get_jobs\n",
      "    joblist = self._parse_joblist_output(retval, stdout, stderr)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/schedulers/plugins/pbsbaseclasses.py\", line 405, in _parse_joblist_output\n",
      "    raise SchedulerParsingError('There are lines without equals sign.')\n",
      "aiida.schedulers.scheduler.SchedulerParsingError: There are lines without equals sign.\n",
      "01/29/2025 07:05:44 PM <1456420> aiida.schedulers.plugins.pbsbaseclasses: [ERROR] There are lines without equals sign! [' case \\\\\"$-\\\\\" in ', ' *v*x*)', ' ;; *v*)', ' ;; *x*)', ' ;; *)', ' ;; esac; fi; unset _mlre _mlIFS; if [ -n \\\\\"${IFS+x}\\\\\" ]; then', ' if [ -n \\\\\"`eval \\\\\\'echo ${\\\\\\'$_mlv\\\\\\'+x}\\\\\\'`\\\\\" ]; then', ' eval `eval ${_mlre} /usr/bin/tclsh /usr/share/Modules/libexec/modulecmd.tcl bash \\\\\\'\\\\\"$@\\\\\"\\\\\\'`; else', ' unset IFS; fi; unset _mlre _mlv _mlrv _mlIFS; if [ -n \\\\\"${_mlshdbg:-}\\\\\" ]; then', ' echo \\\\\"Switching to Modules $swname version\\\\\"; source /usr/share/Modules/init/bash; else', ' eval \\\\\"module $@\\\\\"; else']\n",
      "01/29/2025 07:05:44 PM <1456420> aiida.engine.transports: [ERROR] Exception whilst using transport:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/engine/transports.py\", line 106, in request_transport\n",
      "    yield transport_request.future\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 109, in _get_jobs_from_scheduler\n",
      "    scheduler_response = scheduler.get_jobs(**kwargs)\n",
      "                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/schedulers/scheduler.py\", line 361, in get_jobs\n",
      "    joblist = self._parse_joblist_output(retval, stdout, stderr)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/schedulers/plugins/pbsbaseclasses.py\", line 405, in _parse_joblist_output\n",
      "    raise SchedulerParsingError('There are lines without equals sign.')\n",
      "aiida.schedulers.scheduler.SchedulerParsingError: There are lines without equals sign.\n",
      "\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-89' coro=<JobsList._ensure_updating.<locals>.updating() done, defined at /home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py:179> exception=SchedulerParsingError('There are lines without equals sign.')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/asyncio/tasks.py\", line 314, in __step_run_and_handle_result\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 181, in updating\n",
      "    await self._update_job_info()\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 132, in _update_job_info\n",
      "    self._jobs_cache = await self._get_jobs_from_scheduler()\n",
      "                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 109, in _get_jobs_from_scheduler\n",
      "    scheduler_response = scheduler.get_jobs(**kwargs)\n",
      "                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/schedulers/scheduler.py\", line 361, in get_jobs\n",
      "    joblist = self._parse_joblist_output(retval, stdout, stderr)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/schedulers/plugins/pbsbaseclasses.py\", line 405, in _parse_joblist_output\n",
      "    raise SchedulerParsingError('There are lines without equals sign.')\n",
      "aiida.schedulers.scheduler.SchedulerParsingError: There are lines without equals sign.\n",
      "01/29/2025 07:05:44 PM <1456420> aiida.orm.nodes.process.calculation.calcjob.CalcJobNode: [ERROR] iteration 3 of do_update excepted, retrying after 80 seconds\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/engine/utils.py\", line 205, in exponential_backoff_retry\n",
      "    result = await coro()\n",
      "             ^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/tasks.py\", line 195, in do_update\n",
      "    job_info = await cancellable.with_interrupt(update_request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/engine/utils.py\", line 115, in with_interrupt\n",
      "    result = await next(wait_iter)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/asyncio/tasks.py\", line 631, in _wait_for_one\n",
      "    return f.result()  # May raise f.exception().\n",
      "           ^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/asyncio/futures.py\", line 202, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 132, in _update_job_info\n",
      "    self._jobs_cache = await self._get_jobs_from_scheduler()\n",
      "                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 109, in _get_jobs_from_scheduler\n",
      "    scheduler_response = scheduler.get_jobs(**kwargs)\n",
      "                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/schedulers/scheduler.py\", line 361, in get_jobs\n",
      "    joblist = self._parse_joblist_output(retval, stdout, stderr)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/schedulers/plugins/pbsbaseclasses.py\", line 405, in _parse_joblist_output\n",
      "    raise SchedulerParsingError('There are lines without equals sign.')\n",
      "aiida.schedulers.scheduler.SchedulerParsingError: There are lines without equals sign.\n",
      "01/29/2025 07:07:05 PM <1456420> aiida.schedulers.plugins.pbsbaseclasses: [ERROR] There are lines without equals sign! [' case \\\\\"$-\\\\\" in ', ' *v*x*)', ' ;; *v*)', ' ;; *x*)', ' ;; *)', ' ;; esac; fi; unset _mlre _mlIFS; if [ -n \\\\\"${IFS+x}\\\\\" ]; then', ' if [ -n \\\\\"`eval \\\\\\'echo ${\\\\\\'$_mlv\\\\\\'+x}\\\\\\'`\\\\\" ]; then', ' eval `eval ${_mlre} /usr/bin/tclsh /usr/share/Modules/libexec/modulecmd.tcl bash \\\\\\'\\\\\"$@\\\\\"\\\\\\'`; else', ' unset IFS; fi; unset _mlre _mlv _mlrv _mlIFS; if [ -n \\\\\"${_mlshdbg:-}\\\\\" ]; then', ' echo \\\\\"Switching to Modules $swname version\\\\\"; source /usr/share/Modules/init/bash; else', ' eval \\\\\"module $@\\\\\"; else']\n",
      "01/29/2025 07:07:05 PM <1456420> aiida.engine.transports: [ERROR] Exception whilst using transport:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/engine/transports.py\", line 106, in request_transport\n",
      "    yield transport_request.future\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 109, in _get_jobs_from_scheduler\n",
      "    scheduler_response = scheduler.get_jobs(**kwargs)\n",
      "                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/schedulers/scheduler.py\", line 361, in get_jobs\n",
      "    joblist = self._parse_joblist_output(retval, stdout, stderr)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/schedulers/plugins/pbsbaseclasses.py\", line 405, in _parse_joblist_output\n",
      "    raise SchedulerParsingError('There are lines without equals sign.')\n",
      "aiida.schedulers.scheduler.SchedulerParsingError: There are lines without equals sign.\n",
      "\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-90' coro=<JobsList._ensure_updating.<locals>.updating() done, defined at /home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py:179> exception=SchedulerParsingError('There are lines without equals sign.')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/asyncio/tasks.py\", line 314, in __step_run_and_handle_result\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 181, in updating\n",
      "    await self._update_job_info()\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 132, in _update_job_info\n",
      "    self._jobs_cache = await self._get_jobs_from_scheduler()\n",
      "                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 109, in _get_jobs_from_scheduler\n",
      "    scheduler_response = scheduler.get_jobs(**kwargs)\n",
      "                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/schedulers/scheduler.py\", line 361, in get_jobs\n",
      "    joblist = self._parse_joblist_output(retval, stdout, stderr)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/schedulers/plugins/pbsbaseclasses.py\", line 405, in _parse_joblist_output\n",
      "    raise SchedulerParsingError('There are lines without equals sign.')\n",
      "aiida.schedulers.scheduler.SchedulerParsingError: There are lines without equals sign.\n",
      "01/29/2025 07:07:05 PM <1456420> aiida.orm.nodes.process.calculation.calcjob.CalcJobNode: [ERROR] iteration 4 of do_update excepted, retrying after 160 seconds\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/engine/utils.py\", line 205, in exponential_backoff_retry\n",
      "    result = await coro()\n",
      "             ^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/tasks.py\", line 195, in do_update\n",
      "    job_info = await cancellable.with_interrupt(update_request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/engine/utils.py\", line 115, in with_interrupt\n",
      "    result = await next(wait_iter)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/asyncio/tasks.py\", line 631, in _wait_for_one\n",
      "    return f.result()  # May raise f.exception().\n",
      "           ^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/asyncio/futures.py\", line 202, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 132, in _update_job_info\n",
      "    self._jobs_cache = await self._get_jobs_from_scheduler()\n",
      "                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 109, in _get_jobs_from_scheduler\n",
      "    scheduler_response = scheduler.get_jobs(**kwargs)\n",
      "                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/schedulers/scheduler.py\", line 361, in get_jobs\n",
      "    joblist = self._parse_joblist_output(retval, stdout, stderr)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/hirotosaito/miniconda3/envs/mae/lib/python3.12/site-packages/aiida/schedulers/plugins/pbsbaseclasses.py\", line 405, in _parse_joblist_output\n",
      "    raise SchedulerParsingError('There are lines without equals sign.')\n",
      "aiida.schedulers.scheduler.SchedulerParsingError: There are lines without equals sign.\n",
      "01/29/2025 07:09:53 PM <1456420> aiida.orm.nodes.process.calculation.calcjob.CalcJobNode: [WARNING] could not parse scheduler output: the `_scheduler-stderr.txt` file is missing\n",
      "01/29/2025 07:09:53 PM <1456420> aiida.orm.nodes.process.calculation.calcjob.CalcJobNode: [WARNING] could not parse scheduler output: the `_scheduler-stdout.txt` file is missing\n"
     ]
    }
   ],
   "source": [
    "from aiida.engine import submit, run\n",
    "calcjob_node = run(builder)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "-310.56907003575"
      ]
     },
     "execution_count": 18,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "node = load_node(179)\n",
    "d = node.get_dict()\n",
    "d['energy']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "mae",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
